# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        echelle:
            quality: 75
            filters:
                scale:
                    dim: [ 300, 300 ]
        
        carre:
            quality: 75
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: outbound
                    allow_upscale: true
        carrept:
            quality: 75
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
                    allow_upscale: true
        firstImg:
            quality: 75
            filters:
                scale:
                    dim: [ 2000, 2000 ]